### PR TITLE
fix decompression of arm9 binary for Volt White 2 and Blaze Black 2

### PR DESCRIPTION
**Pull request by piratesephiroth**
(and perhaps other romhacks)

### CODE REVIEW

**Comment by NightYoshi370** [comment]
Did you test this before hand?

**Comment by Mr-Gela** [comment]
If you can provide the compiled commit I'll test it myself

**Comment by piratesephiroth** [comment]
[nds-bootstrap-bb2-vw2.zip](https://github.com/ahezard/nds-bootstrap/files/2303576/nds-bootstrap-bb2-vw2.zip)

**Comment by Mr-Gela** [comment]
Still an error screen upon launch.

**Comment by piratesephiroth** [comment]
If you're not using the lastest DSiMenu then you replaced the wrong file

**Comment by piratesephiroth** [comment]
the name used by old versions was "release-bootstrap.nds" and now it's "nds-bootstrap-release.nds"

**Comment by piratesephiroth** [comment]
though I only tested the vanilla version, not the complete one.

**Comment by Stack3r** [comment]
So does that bootstrap edit only fix compression with volt2 and blaze2?

**Comment by Mr-Gela** [comment]
Awesome. It does seem to work now after running it from DSimenu++ instead of through Forwarder3DS.

**Comment by Robz8** [comment]
Yeah, the SD forwarder template hasn't been updated to use the renamed bootstrap yet.

**Pull request merged**
