### PR TITLE
Fix Castlevania Portrait of Ruin

### PR DESCRIPTION
**Pull request by piratesephiroth**

### CODE REVIEW

**Comment by Robz8** [comment]
So this works?
Last time I tried putting that in, it froze with a white screen.

**Comment by piratesephiroth** [comment]
yeha, I got the patches from an old thread on gbatemp

https://gbatemp.net/threads/which-flashcart-for-castlevania-por.343239/page-2#post-4559271

**Comment by Stack3r** [comment]
So mine will get stuck at a black screen after logos, on latest unofficial

**Comment by piratesephiroth** [comment]
you have to set it to use the Release bootstrap

**Pull request merged**
