### PR TITLE
Dsi: Add "USE_ARM7_DONOR" option, fix potential crash, and add LED option

### PR DESCRIPTION
**Pull request by Robz8**
1. "USE_ARM7_DONOR" should be useful for TWLoader (and in the future, SRLoader) per-game settings.
2. To fix a potential crash, initMBK has been moved to before the ROM starts.
3. Since ARM7 SCFG returns 0 due to it being locked, it's been removed from debug output.
4. A new option has been added to the .ini file, called "ROMREAD_LED".
To use no LED as ROM read indicator, set it to 0.
To use WiFi LED as ROM read indicator, set it to 1.
To use power LED (turn to purple) as ROM read indicator, set it to 2.

### CODE REVIEW

**Comment by piratesephiroth** [comment]
yeah, on the 3DS we can press home then use start +up/down to adjust brightness and left/right to toggle power saving from inside both DSiware and GBA

**Comment by Margen67** [comment]
Why are there two PRs? #83

**Comment by Robz8** [comment]
@Margen67 One for 3DS version, and one for DSi version.

**Comment by Robz8** [comment]
@ahezard Ready to merge!

**Comment by Robz8** [comment]
OK, it's ready.

**Comment by piratesephiroth** [comment]
is the new LED thing exclusive to the DSi branch?

**Comment by ApacheThunder** [comment]
For now yes. The 3DS branch is able to switch into NTR mode properly so this locks out the LED stuff. Plus I think even TWL mode it might not work. 3DS doesn't quite replicate all of the DSi's functionality. :(

**Comment by piratesephiroth** [comment]
Could the LED thing be adapted to the 3DS by changing the colors of one of the screens as the selected game is starting?
(like Open PS2 Loader's "debug colors")

**Comment by Robz8** [comment]
Yeah, that's possible.

**Comment by Valeri0p** [comment]
Maybe only some pixels of the screen? :D

**Pull request merged**
