### PR TITLE
Split and refactor card_patcher.c

### PR DESCRIPTION
**Pull request by damianoamatruda**

### CODE REVIEW

**Comment by damianoamatruda** [comment]
What games don’t work? Do they work with c54e26e?

**Comment by piratesephiroth** [comment]
>What games don’t work? 
The Castlevanias, for example.

Do they work with c54e26e?
yes, they do

**Comment by damianoamatruda** [comment]
Ok, thank you very much

**Comment by piratesephiroth** [comment]
>Does it work now with the other games, too?

yeah, you seem to have fixed it.

Something interesting is that Portrait of Ruin displays that visual glitch at the bottom of the screens when run in TWL speed if I build it myself with the latest devkitarm.

This glitch does not happen with your refactor.

**Comment by ahezard** [comment]
It would be good to have the file card_patcher.c splitted into card_patcher_arm7.c  card_patcher_arm9.c and card_patcher_common.c

**Comment by ahezard** [comment]
The split between card_finder / card_patcher that you did is also good. It makes things more maintainable. Good job.

**Comment by ahezard** [comment]
Would it be too much to ask you to apply these changes to the sdk5 branch as well damianoamatruda?

**Comment by damianoamatruda** [comment]
@ahezard Thank you for your appreciation. I’ll try it willingly

**Pull request merged**
