### PR TITLE
Move fastCopy32 implementation from assembly to C

### PR DESCRIPTION
**Pull request by CJKay**
This should help with converting some of the card engine to
THUMB. It has been tested successfully with the European Bomberman
ROM.

### CODE REVIEW

**Comment by maorninja** [comment]
Wow. Nice.

Although, Sorry for being ignorant, but was there any problem with the way it was done before?

**Comment by CJKay** [comment]
There is nothing particular superior about this method, but a number of reports suggest the Pokémon games aren't booting because "no THUMB version of the SD read code is implemented". I figured here would be a good place to start trying to understand the issue, and this is just my first minor contribution.

I'm sure this could have been written in THUMB assembly, but it was simply easier to just port it to C. :-)

**Comment by Gericom** [comment]
Why would you want this, switching from arm to thumb and back is no problem and I think they meant the thumb version of the sdk here.

**Comment by CJKay** [comment]
Well, feel free to -1 if you don't like it, I'm just looking for some more information on this particular issue.

**Comment by Necklaces** [comment]
Just curious, I'm no C or Assembly expert but,

Whats the difference/advantage to doing this:
```C
void fastCopy32(const struct fc32_chunk *src, struct fc32_chunk *dest, u32 len){
  do {
    *dest = *src;
    
    len -= sizeof(*dest);
  } while (len > 0);
  
}
```

Rather than just this:
```C
void fastCopy32(const struct fc32_chunk *src, struct fc32_chunk *dest){
  *dest = *src;  
}
```
?

**Comment by CJKay** [comment]
It doesn't handle the case where len > 32.

**Comment by Morten242** [comment]
In confused. Doesn't it only reassign the same location over and over?

**Comment by CJKay** [comment]
Ah, I see - well spotted. I'm going to abandon this patch anyway as I've moved onto other projects and this isn't particularly helpful to the project.

**Comment by ahezard** [comment]
Too bad, this patch is not useful indeed since there is no problem with this function as it is, even with a thumb game. To support thumb games it would be needed to : 
1) signatures of the thumb card read and save functions for the different sdk version have to be inserted into card_patcher.c
2) ASM patches into ARM7 and ARM9 card_engine_header.s have to be rewritten
Thank you for your tentative of contribution anyway and feel free to submit a pull request anytime again.

**Comment by Necklaces** [comment]
How do we get these signatures? (btw, do you frequent an IRC channel where we might look into solving these issues together or something? Mailing list?)

**Comment by ahezard** [comment]
You get the signatures by reverse engineering ARM binaries of games that uses thumb with a disassembler. You can contact me on discord (I am on the gbatemp server) or pm me on gbatemp.

**Pull request closed without merging**
