### PR TITLE
Refine code and make patching generally faster

### PR DESCRIPTION
**Pull request by damianoamatruda**

### CODE REVIEW

**Comment by ahezard** [comment]
Why did you changed
-void i2cDelay() {
by
+void i2cDelay(void) {
There is a lot of changes like that and I do not get the added value of doing this.

**Comment by ahezard** [comment]
The optimisation of the findOffset function seems well done

**Comment by ahezard** [comment]
Sadly there was an issue with PR #332 so now this one is conflicting

**Comment by ahezard** [comment]
I have tested PR 332 with a couple of games : kirby canvas curse and castlevania dawn of sorrow and they were not anymore on a dsi

**Comment by damianoamatruda** [comment]
I reimplemented the previous finder algorithm and made some changes which brought the original compatibility back. Kirby Canvas Curse and other thumb games work again now

**Pull request merged**
