### PR TITLE
Support SDKs 1-4 and SDK 5 games in one build

### PR DESCRIPTION
**Pull request by damianoamatruda**
The separate build of nds-bootstrap for SDK 5 games and the branch ‘sdk5’ are no longer needed.

### CODE REVIEW

**Comment by piratesephiroth** [comment]
whoa

**Comment by ahezard** [comment]
Thanks a lot for this contribution. I am impressed. Sadly I do not have so much time to test right now.

**Comment by ahezard** [comment]
I got a white screen with pokemon black.

**Comment by ahezard** [comment]
Other sdk5 games seems to works, can someone test with pokemon black (v1) ?

**Comment by Stack3r** [comment]
Does black2 work?

**Comment by Kalanyr** [comment]
I don't have a build environment setup at the moment but I can test Pokemon B/W/B2/W2 if someone posts a build.

**Comment by piratesephiroth** [comment]
@Kalanyr 
[release-bootstrap-00527d0.zip](https://github.com/ahezard/nds-bootstrap/files/2259007/release-bootstrap-00527d0.zip)

**Comment by Kalanyr** [comment]
@piratesephiroth 
Thanks. Will test now.

**Comment by Kalanyr** [comment]
Pokemon Black (Australian launch version) dumped with GM9  + no AP Patches +  running at TWL speeds + Asynch Prefetch = Notably Slow to Load +White Screen on boot

Pokemon Black (Australian launch version) dumped with GM9  + no AP Patches +  running at NDS speeds + No Asynch Prefetch = Notably Slow to Load +White Screen on boot

Pokemon Black (Australian launch version) dumped on a DS years ago + AP Fix (not sure I have the non-AP Fixed version of this anymore) +  running at NDS speeds + No Asynch Prefetch = Notably Slow to Load (possibly a tad less slow) +White Screen on boot

So yeah seems Pokemon Black is broken.   Will check White now.

**Comment by Kalanyr** [comment]
Decided to check Black 2 first instead  

Pokemon Black 2 (Australian launch version) dumped with GM9 +  AP Patches + running at TWL speeds + Asynch Prefetch = White Screen on boot


So as a preliminary it looks like DSi-enhanced Pokemon doesn't like something about this .

(Pokemon Platinum does work though)

**Comment by Kalanyr** [comment]
Pokemon White (Australian launch version) dumped with GM9 + AP Patches + running at TWL speeds + Asynch Prefetch = White Screen on boot

Pokemon White 2 (Australian launch version) dumped with GM9 + AP Patches + running at TWL speeds + Asynch Prefetch = White Screen on boot


(I can try other combinations if it would be useful but it doesn't seem like it would be to me right now so I'll stop here for the moment)

**Comment by FM1337** [comment]
Could you try some other DSI Enhanced games and see what results you get?

**Comment by Kalanyr** [comment]
Let me dig up a list of DSI-enhanced games and see if I have any to test with (I have Pokemon Conquest but that didn't work before anyway so I need to find some other stuff).

**Comment by Kalanyr** [comment]
I guess Pokemon Conquest was fixed at some point and I missed that.  I decided to test it just in case. 

It runs both on this build and  the last official release. So some DSI-enhanced games are working at least. 

That's something.

**Comment by Kalanyr** [comment]
The original Japanese version of New Mystery works fine too.  

So it just seems to be Pokemon B/W/B2/W2 as best I can tell. So it must be something specific about them.

**Comment by FM1337** [comment]
Huh interesting

**Comment by Stack3r** [comment]
Maybe also the reason those two sets of games are the only ones that have like a lag during gameplay

**Comment by FM1337** [comment]
Can confirm that white 2 and white are still having the white screen issue.

**Comment by damianoamatruda** [comment]
@ahezard, I appreciate you like my work. As far as the problem with “Pokémon Black” and “Pokémon White” is concerned, I’m looking for a fix.

**Comment by damianoamatruda** [comment]
I solved the problem with “Pokémon Black Version” and “Pokémon White Version” in 177389e by changing the start address of ARM9 card engine’s memory region to 0x02700000.

**Comment by FM1337** [comment]
Does this also fix white 2 and black 2?

**Comment by Stack3r** [comment]
@damianoamatruda does BW run cart speed still?

**Comment by Kalanyr** [comment]
If someone wants to post a build I'm happy to test again.

**Comment by damianoamatruda** [comment]
@FM1337, I don’t know if it fixes “Pokémon Black 2” and “Pokémon White 2”, but I don’t think so.

@Stack3, “Pokémon Black Version” and “Pokémon White Version” seem to work at cart speed as previously.

@Kalanyr, this is the new build: [nds-bootstrap-177389e.zip](https://github.com/ahezard/nds-bootstrap/files/2260689/nds-bootstrap-177389e.zip)

**Comment by Kalanyr** [comment]
Pokemon White 2 is fixed , so chances are Black 2 is as well. I'll test it next.

Then I'll check B/W speed after that (if it's running at cart speed its actually a slight improvement from the last nightly I used which has occasional lag problems in eg Opelucid city)

**Comment by FM1337** [comment]
I don't think there's any possible way to improve the cart speed for black/white/white2/black2

**Comment by Kalanyr** [comment]
Seems like the comparability is equivalent to the split builds again now at least from what I had handy to test.  


@FM1337
There might not be just noting that it doesn't always run at cart speed (and that it didn't before either).

**Pull request merged**
