### PR TITLE
Remove bad word

### PR DESCRIPTION
**Pull request by FlameKat53**
no bad words in ahezard’s nds-bootstrap!

### CODE REVIEW

**Comment by arraystock** [comment]
**Hello, good friend!**

**Comment by FlameKat53** [comment]
Epicpkmn11 - lol, this is a PG nds file booter ;P

**Comment by chyyran** [comment]
Duff is a reference to [Duff's device](https://en.m.wikipedia.org/wiki/Duff%27s_device) which is an optimization method tonccpy uses.

**Comment by FlameKat53** [comment]
o

**Pull request merged**
