### PR TITLE
Use libeasysave instead of libeasykey

### LINKED ISSUE #733: Semicolon in ROM name causes a failure to load
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release v0.22.0
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### Expected behaviour

Guess.

### Actual behaviour

The game fails to load, resulting in a black top screen and white bottom screen.

### Steps to reproduce

1. Put a semicolon in the filename of a ROM
2. Load that ROM in nds-bootstrap

### PR DESCRIPTION
**Pull request by arraystock**
Far better API and overall better & more efficient implementation
Also fixes #733

### CODE REVIEW

**Comment by arraystock** [comment]
I've gotten it working under retail, hb and b4ds to go..

**Comment by arraystock** [comment]
Okay. Everything here is now using libeasysave. I have tested both retail and homebrew, but I have not yet tested the B4DS version.

**Comment by NightYoshi370** [comment]
Why'd you change indentation?

**Comment by arraystock** [comment]
My editor has an auto code format feature, I disabled it halfway through my PR. If it's an annoyance, I can go back and properly re-indent it 😄

**Comment by NightYoshi370** [comment]
That'd be nice, since we'd like to keep a consistent code formatting style, and see what lines have actually been changed

**Comment by arraystock** [comment]
Also, as a side-note:
It would be nice to have a project-wide clang-format file. Something like this might be worth looking into: https://github.com/johnmcfarlane/unformat
But that's out of the scope of this PR.

**Comment by arraystock** [comment]
There!

**Comment by RocketRobz** [comment]
The B4DS build also works.

**Pull request merged**
